development:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu, sfisher@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  "" 
  host_for_email_links:   http://dmp.ruf.uni-freiburg.de

development_nonlocal:
  development

stage:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""
  host_for_email_links:   http://dmp.ruf.uni-freiburg.de

stage_development:
  stage

production:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""
  host_for_email_links:   http://dmp.ruf.uni-freiburg.de

production_development:
  production


test:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""

test_nonlocal:
  development
